tes2/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views


urlpatterns = [
    path("", views.pagina_principal, name = "Pagina Principal"),
    path("pruebas", views.pruebas_html, name = "pruebas"),
    path("login", LoginView.as_view(template_name = "tes2/login.html", redirect_authenticated_user=True), name = "login" ),
    path("logout", LogoutView.as_view(template_name = "tes2/logout.html"), name  = "logout"),
    path("registro_equipo", views.creacion_equipo, name = "Registro de Equipo"),
    path("mapa",views.mapa ),
    path("equipos", views.lista_equipos),
    path("browse/<num_eq>", views.vista_detalle_todos),
    path("registro_equipo/<str:tipo_maq>/<str:id>", views.forma_equipos),
    path("browse",views.busq_principal, name= "busqueda"),
    path("mi_cuenta", views.pag_principlal_usuario, name = "mi-cuenta"),
    path("mi_cuenta/mis_equipos", views.lista_equipos_usuario, name = "mi-maq"),
    path("mi_cuenta/mis_transacciones", views.lista_transacciones_usuario, name = "mis-contratos"),
    path("registro", views.registro_usuario, name = "reg_usuario"),
    path("registro_ubicacion", views.registro_ubicacion, name = "reg_ubicacion"),
    path("registro/datos_int", views.datos_interesado, name ="datos-interesado"),
    path("renta/<num_eq>", views.renta_inicial, name = "renta"),
    path("venta/<num_eq>", views.venta_inicial, name = "venta"),
    path("fechas_renta/<num_eq>",views.api_fechas, name = "API-fechas"),
    path("mis_solicitudes",views.solicitudes_usuario, name = "noti"),
    path("mis_solicitudes/<id_sol>",views.solicitudes_especificas, name = "noti-esp"),
    path("mis_solicitudes/<id_sol>/rsp", views.respuesta_sol_eq),
    path("mi_cuenta/ubicaciones",views.ubicaciones_usuario, name = "ubicaciones"),
    path("mi_cuenta/ubicaciones/<id_ub>",views.ubicacion_especifica, name = "ub-esp"),
    path("mi_cuenta/ubicaciones/<id_ub>/eliminar", views.elimina_ubicacion, name ="e-ub"),
    path("mi_cuenta/ubicaciones/<id_ub>/eliminar/equipos", views.elim_equipos_ub, name = "e-ub-eq"),
    path("mi_cuenta/equipos/<id_eq>/eliminar", views.elimina_eqipo, name = "el-eq"),
    path("mi_cuenta/equipos/<id_eq>", views.vista_eq_usuario),
    path("mi_cuenta/mis_tr/<id_tr>", views.vista_individual_transaccion),
    path("mi_cuenta/mis_tr/<id_tr>/cancelar", views.cancela_transaccion),
    path("mi_cuenta/mis_mensajes", views.mensajes, name = "mensajes"),
    path("mensajes/<id_conv>", views.consigue_mensajes),
    path("conv/<id_conv>", views.nuevo_msj),
    path("browse_mapa", views.busqueda_mapa, name="busq-mapa"),
    path("solicitudes_abiertas/gen", views.solicitud_abierta_inicial),
    path("solicitudes_abiertas", views.solicitudes_abiertas),
    path("genera_reporte", views.reportes),
]

tesis/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("tes2.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

tes2/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.deletion import CASCADE
from django.db.models.fields import PositiveSmallIntegerField


# Create your models here.

OPCIONES_TIPO = (
    ("tractor","TRACTOR"),
    ("arado","ARADO"),
    ("rastra","RASTRA"),
    ("sembradora", "SEMBRADORA"),
    ("pulverizadora","PULVERIZADORA"),
    ("cosechadora","COSECHADORA"),
    ("otros","OTROS"),    
)
OPCIONES_USO = (
    ("venta", "Venta"),
    ("renta", "Renta"),
    ("ambos", "Ambos")
)

OPCIONES_ESTADO = (
    ("malo", "Malo"),
    ("regular", "Regular"),
    ("buena", "Buena"),
    ("excelente", "Excelente"),
)

OPCIONES_STATUS = (
    ("activo", "Activo"),
    ("apartado", "Apartado"),
    ("rentado", "Rentado"),
    ("inactivo", "Inactivo"),
    ("eliminado", "Eliminado"),
)

OPCIONES_STATUS_TRANSACCION = (
    ("1", "Completada"),
    ("2", "Abortada"),
    ("3", "En Ejecución"),
    ("4", "En Espera"),
)

OPCIONES_STATUS_SOLICITUD = (
    ("1", "En Espera"),
    ("2", "Aceptada"),
    ("3", "Rechazada"),
)


class Usuario(models.Model):
    id_usuario = models.OneToOneField(User, null = True, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=25, null = True, blank= True)
    apellido_1 = models.CharField(max_length=30, null = True)
    apellido_2 = models.CharField(max_length= 30, null = True, blank=True)
    telefono = models.CharField(max_length= 20, null = True, blank=True)
    celular = models.CharField(max_length= 20)
    nivel_permisos = models.PositiveSmallIntegerField(default=1)
    usuario_activo = models.BooleanField(default=True)

    def __str__(self):
        return self.nombre


class Ubicacion(models.Model):
    id_ubicacion = models.CharField(max_length=200, primary_key=True)
    id_usuario   = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    alias = models.CharField(max_length=200)
    coord_x = models.CharField(max_length= 20)
    coord_y = models.CharField(max_length= 20)
    estado = models.CharField(max_length=70, null= True)
    municipio = models.CharField(max_length=100, null= True)
    referencias = models.CharField(max_length=200)
    area = models.PositiveSmallIntegerField(default= 1)
    eliminado = models.BooleanField(default= False)

    def __str__(self):
        return self.alias


class Equipo(models.Model):
    num_equipo = models.CharField(max_length= 10, primary_key= True)
    nombre_equipo = models.CharField(max_length=100, default= "")
    id_dueño = models.ForeignKey(User, on_delete= models.CASCADE)
    tipo_equipo = models.CharField(max_length=20, choices= OPCIONES_TIPO, null = True, blank= False)
    descripcion = models.CharField(max_length= 200)
    marca = models.CharField(max_length= 20, default= "")
    modelo = models.CharField(max_length= 20, default= "")
    año = models.PositiveSmallIntegerField(default=1993)
    estado_equipo = models.CharField(choices=OPCIONES_ESTADO, max_length=10)
    donde_esta = models.ForeignKey(Ubicacion,null = True, on_delete= models.SET_NULL, related_name= "donde_esta")
    ubicacion_base = models.ForeignKey(Ubicacion, on_delete= models.SET_NULL, null = True, related_name= "ubcacion_base")
    para_que = models.CharField(choices= OPCIONES_USO, max_length= 10)
    hecatreas_trabajadas = models.FloatField( default = 1)
    precio_venta = models.FloatField(null=True)
    precio_renta_dia = models.FloatField(null=True)
    status = models.CharField(choices=OPCIONES_STATUS, max_length=10)

    def __str__(self):
        return self.nombre_equipo
    
    @property
    def que_es(self):
        return self.tipo_equipo.capitalize()


###################################################################################### Equipos "de apoyo" #############################################################################
class Tractor(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)
    potencia = models.CharField(max_length=4)
    estrias_PTO = models.CharField(max_length= 2)
    enganche_tres_puntos = models.BooleanField()
    traccion = models.CharField(max_length=9)
    cabina = models.CharField(max_length=10)

    @property
    def tipo_tractor(self):
        if self.potencia <= 115:
            return "Pequeño"
        if self.potencia > 115 and self.potencia <= 165:
            return "Mediano"
        if self.potencia > 165:
            return "Grande"


class Sembradora(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)    
    tipo = models.CharField(max_length= 20)
    fertilizadora = models.BooleanField(default=False)
    no_tolvas = models.PositiveSmallIntegerField()
    neumatica_mecanica = models.CharField(max_length=15)


class Arado(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True) 
    tipo = models.CharField(max_length= 20)
    reversible = models.BooleanField(default= False)
    no_cuerpos = PositiveSmallIntegerField()
    neumatica_mecanica = models.CharField(max_length= 15, null = True)


class Pulverizadora(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)
    autopropulsada = models.BooleanField(default= False)
    tamaño_tanque = models.PositiveSmallIntegerField()
    no_boquillas = PositiveSmallIntegerField()
    capacidad_bomba = models.PositiveSmallIntegerField()


class Rastra(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)
    acople = models.CharField(max_length= 20)
    tipo_cuerpo = models.CharField(max_length=20)
    no_cuerpos = PositiveSmallIntegerField()
    disposicion_cuerpos = models.CharField(max_length= 15)


class Cosechadora(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)
    tipo_cultivo = models.CharField(max_length= 20)
    potencia = PositiveSmallIntegerField()
    capacidad_granos = models.PositiveSmallIntegerField(null = True)
    tasa_descarga = models.PositiveSmallIntegerField(null = True)


class Otros_equipos(models.Model):
    id_equipo = models.OneToOneField(Equipo, max_length=10, on_delete= models.CASCADE, primary_key=True)
    potencia = models.PositiveSmallIntegerField(null = True)
    producto_agricola = models.CharField(max_length=30)

########################################### Termina Equipos "de apoyo" ####################################

class Transaccion(models.Model):
    id_transaccion = models.AutoField(max_length = 10, primary_key=True)
    id_equipo = models.ForeignKey(Equipo, on_delete = models.SET_DEFAULT, default = "0001")
    id_dueño = models.ForeignKey(Usuario, on_delete=models.SET_DEFAULT, default="0001", related_name="dueño_usuario")
    id_arrendatario = models.ForeignKey(Usuario, on_delete = models.SET_DEFAULT, default="0001", related_name="arrendatario_usuario")
    desde_donde = models.ForeignKey(Ubicacion, on_delete = models.SET_DEFAULT, default = "0001", related_name = "desde_donde_ubicacion")
    hacia_donde = models.ForeignKey(Ubicacion, on_delete = models.SET_DEFAULT, default = "0002", related_name = "hacia_donde_ubicacion")
    estatus = models.CharField(choices = OPCIONES_STATUS_TRANSACCION, max_length = 12)
    fecha_inicial = models.DateField(default= "2021-06-22")
    fecha_final = models.DateField(null =True, blank=True)
    importe_total = models.FloatField()
    numero_hectareas = models.IntegerField(default=1)
    tipo_transaccion = models.CharField(max_length = 5)


class Imagen(models.Model):
    id_imagen = models.AutoField(primary_key=True)
    id_equipo = models.ForeignKey(Equipo, on_delete= models.CASCADE, null = True)
    id_usuario = models.ForeignKey(Usuario, on_delete= models.CASCADE, null = True)
    imagen = models.ImageField(upload_to="images/", blank = True)
    es_principal = models.BooleanField(default=False)
    es_identificacion = models.BooleanField(default = False)

    @property
    def imageURL(self):
        try:
            url = self.imagen.url
        except:
            url = ""
        return url


class Solicitud(models.Model):
    """Solicitud de renta o compra de un equipo"""
    id_solicitud = models.AutoField(primary_key = True)
    id_solicitante = models.ForeignKey(Usuario, on_delete= models.CASCADE, related_name = "sol_sol")
    id_dueño_eq = models.ForeignKey(Usuario,on_delete = models.CASCADE, related_name = "sol_dueño", blank=True,null =True)
    id_equipo = models.ForeignKey(Equipo, on_delete=models.SET_NULL, blank=True,null = True)
    tipo_equipo = models.CharField(null = True, blank=True, max_length = 30)
    parametro_1 = models.CharField(null = True, blank=True, max_length = 30)
    parametro_2 = models.CharField(null = True, blank=True, max_length = 30)
    parametro_3 = models.CharField(null = True, blank=True, max_length = 30)
    parametro_4 = models.CharField(null = True, blank=True, max_length = 30)
    parametro_5 = models.CharField(null = True, blank=True, max_length = 30)
    comentario = models.CharField(max_length = 255, null = True, blank = True)
    tipo_operacion = models.CharField(max_length=10)
    a_donde = models.ForeignKey(Ubicacion, on_delete=models.SET_DEFAULT, default="", related_name = "hacia_donde_sol")
    desde_donde = models.ForeignKey(Ubicacion, on_delete=models.SET_NULL, related_name = "dsde_donde_sol", null = True)
    fecha_solicitud = models.DateField()
    fecha_inicio = models.DateField(blank=True,null =True)
    fecha_final = models.DateField(null =True, blank=True)
    estatus = models.CharField( max_length=10, default = "1")
    costo = models.IntegerField(blank=True,null =True)
    hectareas_trabajar = models.PositiveSmallIntegerField(blank=True,null = True)
    tipo_solicitud = models.PositiveSmallIntegerField(default= 1)
        # Tipo de solicitud
        # 1 = "normal",

tes2/templates/tes2/calen.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Calendar</title>
    <link rel = "stylesheet" href="C:\Users\Conagua\Desktop\Tesis\Django_Tesis\Tesis_2\Src\static\css\estilo_cal.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <div class="container con-cal">
        <div class="calendar">
            <div class="month">
                <i class="fas fa-angle-left prev"></i>
                <div class="date">
                    <h1></h1>
                    <p>Jueves 24 de Junio, 2020</p>
                </div>
                <i class="fas fa-angle-right next"></i>
            </div>
            <div class="weekdays">
                <div>Domingo</div>
                <div>Lunes</div>
                <div>Martes</div>
                <div>Miércoles</div>
                <div>Jueves</div>
                <div>Viernes</div>
                <div>Sábado</div>
            </div>
            <div class="days">
            </div>
        </div>
    </div>
    

    <script src = "C:\Users\Conagua\Desktop\Tesis\Django_Tesis\Tesis_2\Src\static\js\calen.js" ></script>
</body>
</html>

tes2/templates/tes2/datos_especificos_usuario.html
{% extends "tes2/main.html" %}


{% block content %}
<div class="container">
    <div class="row center">
        <h1>Datos Personales</h1>
    </div>
    <div class="row">
        <div class="col-4">
            <form class = "form" method = "POST"> {% csrf_token %}
                {{form.as_p}}
                
                <button type ="submit" id = "sbubmit">Ingresar</button>
                
                </form>
        </div>
    </div>
</div>





{% endblock content %}

tes2/templates/tes2/eq_ubicacion.html
{% extends "tes2/main.html" %}
{%load static%}

{% block content %}
<div class="container">
    <div class="row center my-2">
        <h2>Equipos en {{ubicacion.alias}}</h2>
    </div>
    <div class="row">
        <div class = "col-8 center">
            <form class = "form" method = "POST" id = "forma-princ">     {%csrf_token%}
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">No</th>
                        <th scope="col">Nombre</th>
                        <th scope="col">Nueva Ubicación</th>
                    </tr>
                    </thead>
                    <tbody id = "num">
                    {% for eq in equipos %}
                    <tr>  
                        <td>{{ forloop.counter }}</td>
                        <td>{{eq.nombre_equipo|capfirst}}</td>
                        <td>
                            <select id = "op-ub" required class = "form-control" name = "ubicacion-{{eq.num_equipo}}">
                                <option value selected>------------</option>
                                {% for ub in opciones %}
                                <option>{{ub.alias}}</option>                        
                                {% endfor %}
                            </select>
                        </td>
                    </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </form>
            <div class="b-rec">
                <button class="btn btn-primary" id = "btn-si">Aceptar</button>
                <button class="btn btn-danger" id = "btn-no">Cancelar</button>
            </div>
        </div>
    </div>
</div>
{% if messages %}
   <script>
    {% for message in messages %}
        alert("{{ message }}");
    {% endfor %}
   </script>
{% endif %}

<script type="text/javascript" src="{%static 'js/cambio_ub_eq.js'%}"></script>

{% endblock content %}

tes2/templates/tes2/forma_especifica.html
{% extends "tes2/main.html" %}
{% load static %}







{% block content %}
<div class="container">
    <div class="row">
        <div class = "col-3">
            <form class = "form" method = "POST" id = "forma-datos" enctype="multipart/form-data"> {% csrf_token %}
                {{forma.as_p}}
                <input required id = "imgs" name="images" type = "file" multiple>
            </form>
            <div class="derecha">
                <input  type="button" value="Ingresar" onclick="submitForms()"/>
            </div>
        </div>
        <div class="col brd">
            <div class = "row" id ="img-row">
                <span class = "center">Previsualización de Imágenes</span>
                <br>
            </div>           
        </div>
    </div>
</div>



<script src="{%static 'js/forma_especifica.js'%}"></script>

{% endblock content %}

tes2/templates/tes2/index_login.html
{% extends "tes2/main.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-8">
            <div class="row my-3">
                <h1>Nombre Por Definir</h1>
            </div>
            <div class="row">
                <div class="col desc">
                    <p>
                        Sistema de Información para facilitar la interacción entre usuarios <br>interesados en rentar o comprar 
                        equipos agrícolas.
                    </p>
                </div>
            </div>
        </div>
        <div class="col-4">
            <div class="row center mb-2">
                <h2>
                    Busca un Equipo
                </h2>
            </div>
            <div class="row hh">
                <form class = "form-control" id = "la-forma">
                    <div class="mb-3">
                        <label for="tipo_equipo" class = "center" >Tipo de Equipo</label>
                        <select name = "tipo_equipo" id = "tipo_equipo" class ="form-control">
                            <option value = "">Todos</option>
                            <option value = "tractor">Tractor</option>
                            <option value = "arado">Arado</option>
                            <option value = "rastra">Rastra</option>
                            <option value = "sembradora">Sembradora</option>
                            <option value = "pulverizadora">Pulverizadora</option>
                            <option value = "cosechadora">Cosechadora</option>
                            <option value = "otros">Otros</option>
                        </select>

                    </div>
                    <div class="mb-3">
                        <label for="estado" >Estado</label>
                        <select name = "ubicacion_base__estado" id = "estado" class ="form-control">
                            <option value = "">Todos</option>
                        </select>
                    </div>
                    <div class="mb-3 hidden" id = "div-m">
                        <label for="municipio" id = "labelM">Municipio</label>
                        <select name = "ubicacion_base__municipio" id = "municipio" class ="form-control">
                        </select>
                    </div>
                </form>
                <div class="derecha m-2">
                    <button class="btn btn-primary" id = busqueda>Buscar Equipos</button>
                </div>
            </div>
            <div class="row">
                <div class="col derecha" style="margin-top: 100px;">
                    <a class="btn btn-primary" href = "/solicitudes_abiertas">Explorar Solicitudes Abiertas</a>
                </div>                
            </div>
        </div>
    </div>
</div>

<script type="text/javascript" src="{%static 'js/principal.js'%}"></script>


{% endblock content %}

tes2/templates/tes2/login.html
{% extends "tes2/main.html" %}
{% load static %}



<!-- <form class = "form" method = "POST">
{%csrf_token%}
{{form.as_p}}

<button type ="submit" id = "submit">Ingresar</button>

</form> -->


{% block content %}
    <div id="content-container" class="container p-none">
        <div class="lgn-container col-lg-8">
            <form id="login-form" method="post" 
                  action="{% url 'login' %}">
                {% csrf_token %}
                <table class="table">
                    <tr>
                        <td><label for="id_username">Usuario</label></td>
                        <td><input id="id_username" name="username" 
                                   type="text" class="form-control"></td>
                    </tr>
                    <tr>
                        <td><label for="id_password">Contraseña</label></td>
                        <td><input id="id_password" name="password" 
                                   type="password" class="form-control"></td>
                    </tr>
                </table>
                {% if form.errors %}
                    <p class=" label label-danger">
                        Your username and password didn't match. 
                        Please try again.
                    </p>
                {% endif %}

                <input type="submit" value="Login" 
                       class="btn btn-primary pull-right" />
                <input type="hidden" name="next" value="{{ next }}" />
            </form>
        </div>
    </div>
{% endblock content %}

tes2/templates/tes2/pruebas.html
{% extends "tes2/main.html" %}
{% load static %}

{% block content %}
<form class = "form" method = "POST" id = "forma-datos"> {% csrf_token %}
    <input type="hidden" value = "" name = "datos" id ="datos">
    <input type="hidden" value = "" name = "ubi" id ="ubi">

</form>

<button id = "asigna">Dale</button>

<script type="text/javascript">
    const listaMun = []
    const listaCoords = []

    const lasUb = {{ubicacion}}
    console.log(lasUb)


    const datos_dir= async function(ubicacion){
        const llAPI = "AIzaSyA6BgqA2oKejfHVnFodwFPmIDJZDIH6YeE"
        const respo = await fetch(`https://maps.googleapis.com/maps/api/geocode/json?latlng=${ubicacion}&key=${llAPI}`)
        const jsonR = await respo.json()
        let elIndex = jsonR.results.map( res => res.types).findIndex(areg => areg.includes("administrative_area_level_2"))
        if (elIndex == -1){
            elIndex = jsonR.results.map( res => res.types).findIndex(areg => areg.includes("administrative_area_level_3"))
        }
        const municipio = jsonR.results[elIndex].address_components[0].long_name
        const estado = jsonR.results[elIndex].address_components[1].long_name
        listaMun.push([municipio, estado])
        listaCoords.push(ubicacion)




        console.log(municipio, estado)
        datos.value = listaMun;
        ubicaciones.value = listaCoords;

    }

    lasUb.forEach(async function(ub){
        await datos_dir(ub)
        console.log(listaMun)
        console.log(listaCoords)
    })   
    const boton = document.getElementById("asigna");
    const forma = document.getElementById("forma-datos")
    const datos = document.getElementById("datos")
    const ubicaciones = document.getElementById("ubi")

    boton.addEventListener("click",function(){
        forma.submit()
    })

</script>


{% endblock content %}

tes2/templates/tes2/sin_equipos.html
{% extends "tes2/main.html" %}
{% load static %}

{% block content %}

<div class="container">
    <div class="row center">
        <h1>No cuentas con equipos registrados</h1>
        <a class = "btn btn-success mt-4" href = "{% url 'Registro de Equipo' %}"> Registrar un Equipo</a>
    </div>
</div>


{% endblock content %}

tes2/templates/tes2/solicitudes_abiertas_inicial.html
{% extends "tes2/main.html" %}
{% load static %}


{% block content %}

<div class="container">
  <div class="row hh justify-content-center">
      <div class="col-5">
        <form method="POST">{% csrf_token %}
            <p>
                <label for="id_tipo_equipo">Tipo de equipo requerido:</label>
                <select name="tipo_equipo" class="form-control" required id="id_tipo_equipo">
                    <option value ="" selected>Seleccione una opción</option>
                </select>
                </p>
                <div id = "parametros">
        
                </div>
                <p>
    
            <label for="id_a_donde">¿Para que ubicación?</label>
            <select name="a_donde" class="form-control" required id="id_a_donde">
                <option value="" selected>Seleccione una opción</option>
                {% for ub in ubicaciones %}
                <option value = "{{ub.id_ubicacion}}">{{ub}}</option>
                {% endfor %}
            </select>
            </p>
            <p>
                <label for="hectareas_trabajar">Hectáreas que se trabajarán</label>
                <input type="number" required name = "hectareas_trabajar" id = "hectareas_trabajar" class = form-control>
            </p>
            <p>
            <label for="id_tipo_operacion">¿Comprar o Rentar?:</label>
            <select name="tipo_operacion" class="form-control" required id="tipo_operacion">
                <option value="" selected>Seleccione una opción</option>
                <option value="venta">Comprar</option>          
                <option value="renta">Rentar</option>          
            </select>
            </p>
            <div id="fechas">
            </div>
            <p>
                <label for="comentario">Deja un Comentario para tu Solicitud</label>
                <textarea rows =4  cols = "50" name= "comentario", id = "comentario" required></textarea>
            </p> 

            
            <div class="derecha">
                <button type = "submit" class = "btn btn-secondary" id = "next1">Generar Solicitud</button>
            </div>
          </form>
      </div>
  </div>
</div>

<script type="text/javascript" src="{%static 'js/sol_abierta_crea.js'%}"></script>
{% endblock content%}